sonar.projectKey=artus-engineering_n8n-nodes-loki_f771277c-125c-400f-aca0-df3d8c63b594
sonar.sourceEncoding=UTF-8
sonar.sources=nodes,credentials
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*Description.ts
